name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build App
      working-directory: ./monday-dashboard
      run: npm install && npm run build
    - name: Build the Docker image
      working-directory: ./monday-dashboard
      run: docker build . --file dockerfile --tag rdetlaff/monday-dashboard:$(date +%s)

      
