FROM nginx:alpine
COPY /dist/monday-dashboard/browser /usr/share/nginx/html
#copying nginx config from local to image
COPY /nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80/tcp
CMD ["nginx", "-g", "daemon off;"]